#@ load("/values.star", "data")

---
apiVersion: v1
kind: Secret
metadata:
  name: cf-system-cert
  namespace: #@ data.values.system_namespace
stringData:
  tls.key: #@ data.values.system_certificate.key
  tls.crt: #@ data.values.system_certificate.crt
type: kubernetes.io/tls

---
apiVersion: v1
kind: Secret
metadata:
  name: cf-workloads-cert
  namespace: #@ data.values.system_namespace
  annotations:
    kapp.k14s.io/versioned: ""
    kapp.k14s.io/num-versions: "1"
stringData:
  tls.key: #@ data.values.workloads_certificate.key
  tls.crt: #@ data.values.workloads_certificate.crt
type: kubernetes.io/tls
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: cf-workloads-cert
  namespace: #@ data.values.system_namespace
spec:
  delegations:
    - secretName: cf-workloads-cert-ver-1
      targetNamespaces:
      - #@ data.values.workloads_namespace
