---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
metadata:
  name: kapp-contour-rules

templateRules:
- resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: Secret}
  affectedResources:
    objectReferences:
    - path: [spec, delegations, {allIndexes: true}]
      resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: projectcontour.io/v1, kind: TLSCertificateDelegation}
      nameKey: secretName
    - path: [spec, virtualhost, tls]
      resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: projectcontour.io/v1, kind: HTTPProxy}
      nameKey: secretName
