apiVersion: kapp.k14s.io/v1alpha1
kind: Config
metadata:
  name: kapp-routecontoller-contour-rules

templateRules:
- resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: Secret}
  affectedResources:
    objectReferences:
    - path: [data]
      resourceMatchers:
      - andMatcher:
          matchers:
          - apiVersionKindMatcher: {apiVersion: v1, kind: ConfigMap}
          - hasAnnotationMatcher:
              keys:
              - cf-for-k8s.cloudfoundry.org/with-secret-ref
      nameKey: TLS_SECRET_NAME
