#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")
#@ load("/namespaces.star", "system_namespace", "workloads_namespace")

#@ def networking_values():
#@  values = {
#@    "systemNamespace": system_namespace(),
#@    "workloadsNamespace": workloads_namespace(),
#@    "routecontroller": {
#@      "ingressSolutionProvider": data.values.networking.ingress_solution_provider,
#@    },
#@  }
#@  if data.values.networking.ingress_solution_provider == "contour":
#@    values["routecontroller"]["contour"] = {
#@      "tlsSecretName": system_namespace() + "/cf-workloads-cert-ver-1",
#@      "httpsOnly": data.values.gateway.https_only,
#@    }
#@  end
#@  return values
#@ end

#@ networking = library.get("cf-k8s-networking")
--- #@ template.replace(networking.with_data_values(networking_values()).eval())
